name: Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v9

    - name: Install library and dependencies
      run: poetry install

    - name: Install pre-commit
      uses: pre-commit/action@v3.0.1
